### ISSUE TITLE
where is web  frontend ? i add and optis utils

### ISSUE THREAD

**Issue by jambestwick** [rugdocio/honeypot-checker-frontend#2]

**Comment by GuessDragon** [comment]
@jambestwick @carlos-bsc  code is not open soure

**Comment by carlos-bsc** [comment]
HI all, do you need an MIT license on this repo because I can gladly add it :-) which code is not open source?

**Comment by GuessDragon** [comment]
ok,if you want ,I can contibute the rugdoc





------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Tuesday, Dec 21, 2021 10:19 PM
***@***.***&gt;; 
Cc:&nbsp;"Yagami ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [rugdocio/honeypot-checker-frontend] where is web  frontend ? i add and optis utils (#2)





 
HI all, do you need an MIT license on this repo because I can gladly add it :-) which code is not open source?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
